#### Df支持哪些类型的输入输出
- 文件
- 数据库
- web api

主要研究如何从csv当中读取数据，后续如果有其他需求可进一步规划处理

In [1]:
columns = ['Date/Time','Message Type','Security Code','Trade ID','Order ID','Price','Quantity','Trade Type','Trade Time','Side','Order Type','Order Book Position','Aggregated number of shares','Cooling off period Start Time','Cooling off period End Time','VCM Reference Price','VCM Lower Price','VCM Upper Price','Reference Price','Lower Price','Upper Price','Order Imbalance Direction','Order Imbalance Quantity','Suspension Indicator']

#### 如何将csv文件读入DataFrame

使用**read_csv/read_table函数**

#### 如何读取全数据文件（csv当中不包含columns，自定义columns）

在上述函数当中
- 参数header=None
- 参数names指定列名list

In [2]:
import pandas as pd

# df = pd.read_csv('Sample/MC30_AllFB_20210515.csv', header = None, names = columns)
df = pd.read_table('Sample/MC30_AllFB_20210515.csv', sep=',', header = None, names = columns)

C:\AppData\Local\Temp\ipykernel_17556\2002241953.py:4: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_table('Sample/MC30_AllFB_20210515.csv', sep=',', header = None, names = columns)

In [3]:
df.iloc[1:3]

,Date/Time,Message Type,Security Code,Trade ID,Order ID,Price,Quantity,Trade Type,Trade Time,Side,...,Cooling off period End Time,VCM Reference Price,VCM Lower Price,VCM Upper Price,Reference Price,Lower Price,Upper Price,Order Imbalance Direction,Order Imbalance Quantity,Suspension Indicator
1,20210515064845061,21,155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,20210515064845061,21,172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [4]:
df.shape

(452480, 24)

In [5]:
columns = ['Date/Time','Message Type','Security Code','Trade ID','Order ID','Price','Quantity','Trade Type','Trade Time','Side','Order Type','Order Book Position','Aggregated number of shares','Cooling off period Start Time','Cooling off period End Time','VCM Reference Price','VCM Lower Price','VCM Upper Price','Reference Price','Lower Price','Upper Price','Order Imbalance Direction','Order Imbalance Quantity','Suspension Indicator']

In [6]:
df.iloc[:,[0]]

                Date/Time
0       20210515064845061
1       20210515064845061
2       20210515064845061
3       20210515064845061
4       20210515064845061
...                   ...
452475  20210515120801909
452476  20210515120801909
452477  20210515120801909
452478  20210515120801909
452479  20210515120801909

[452480 rows x 1 columns]

In [7]:
df.shape

(452480, 24)

#### 如何处理大型文本文件
- 调整显示参数：pd.options.display.min_rows = 50
- 参数nrows:限制从文件头读入的行数
- chunksize：

In [8]:
# pd.options.display.max_rows = 300
# DataFrame会按照min_rows指定的行数进行显示
pd.options.display.min_rows = 10
df = pd.read_csv('Sample/MC30_AllFB_20210515.csv', header = None, names = columns)

C:\AppData\Local\Temp\ipykernel_17556\1363678544.py:4: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Sample/MC30_AllFB_20210515.csv', header = None, names = columns)

In [9]:
df

,Date/Time,Message Type,Security Code,Trade ID,Order ID,Price,Quantity,Trade Type,Trade Time,Side,...,Cooling off period End Time,VCM Reference Price,VCM Lower Price,VCM Upper Price,Reference Price,Lower Price,Upper Price,Order Imbalance Direction,Order Imbalance Quantity,Suspension Indicator
0,20210515064845061,21,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
1,20210515064845061,21,155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,20210515064845061,21,172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
3,20210515064845061,21,307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,20210515064845061,21,364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452475,20210515120801909,56,83186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
452476,20210515120801909,41,4332,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
452477,20210515120801909,56,4332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
452478,20210515120801909,41,4336,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
452479,20210515120801909,56,4336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN

In [10]:
df['Date/Time'].value_counts()

20210515091500003    407
20210515120600003    368
20210515092017010    288
20210515092017007    276
20210515092015591    262
                    ...
20210515102355289      1
20210515102355314      1
20210515102355319      1
20210515102355348      1
20210515104218086      1
Name: Date/Time, Length: 303901, dtype: int64

In [21]:
chunker = pd.read_csv('Sample/MC30_AllFB_20210515.csv', header = None, names = columns, chunksize = 1000)
price_max = []
for piece in chunker:
   price_max.append(piece['Price'].max())
price_max

[1128.0,
 1130.0,
 1130.0,
 477.8,
 189.2,
 1130.0,
 65.15,
 65.0,
 650.5,
 1128.0,
 1129.0,
 478.2,
 1130.0,
 1130.0,
 1130.0,
 656.5,
 1130.0,
 1130.0,
 1130.0,
 189.3,
 1130.0,
 1129.0,
 1130.0,
 652.0,
 189.1,
 1130.0,
 659.0,
 1130.0,
 1130.0,
 655.0,
 478.2,
 1130.0,
 1129.0,
 189.8,
 478.2,
 652.0,
 1130.0,
 656.0,
 65.2,
 111.2,
 478.2,
 1130.0,
 652.5,
 477.2,
 1137.0,
 1130.0,
 1133.0,
 131.6,
 1130.0,
 653.0,
 1130.0,
 1129.0,
 1130.0,
 478.2,
 1130.0,
 1130.0,
 1130.0,
 654.5,
 1131.0,
 655.0,
 666.0,
 478.0,
 656.0,
 189.2,
 655.5,
 655.5,
 1128.0,
 655.5,
 189.2,
 478.0,
 478.0,
 1131.0,
 189.2,
 189.2,
 477.8,
 1129.0,
 655.5,
 651.0,
 654.5,
 1133.0,
 1130.0,
 1130.0,
 1133.0,
 1132.0,
 1132.0,
 1126.0,
 1131.0,
 664.5,
 1131.0,
 1131.0,
 1133.0,
 665.0,
 1128.0,
 1130.0,
 1131.0,
 655.0,
 1129.0,
 1129.0,
 1134.0,
 1137.0,
 664.5,
 663.0,
 1127.0,
 1128.0,
 1133.0,
 663.5,
 663.5,
 1129.0,
 1128.0,
 655.0,
 1129.0,
 660.0,
 1134.0,
 655.0,
 654.0,
 1131.0,
 654.0,
 654.0,
 1129.0,
 1132.0,
 654.0,
 1132.0,
 1129.0,
 1131.0,
 1129.0,
 1126.0,
 1133.0,
 1133.0,
 660.0,
 1134.0,
 1131.0,
 1128.0,
 653.0,
 1130.0,
 1132.0,
 653.0,
 1130.0,
 653.0,
 1131.0,
 1130.0,
 1129.0,
 1134.0,
 652.5,
 1127.0,
 1131.0,
 1133.0,
 1131.0,
 654.0,
 1133.0,
 1132.0,
 1128.0,
 599.0,
 1126.0,
 1128.0,
 1128.0,
 596.5,
 1130.0,
 1133.0,
 1133.0,
 591.0,
 591.0,
 1131.0,
 591.0,
 1131.0,
 1131.0,
 1130.0,
 591.0,
 1129.0,
 587.5,
 591.0,
 591.0,
 591.0,
 1130.0,
 594.5,
 591.0,
 591.0,
 1129.0,
 1132.0,
 1134.0,
 1127.0,
 1130.0,
 1131.0,
 582.0,
 1134.0,
 1130.0,
 1129.0,
 1133.0,
 1132.0,
 1130.0,
 1134.0,
 1127.0,
 580.0,
 1128.0,
 580.0,
 1131.0,
 1128.0,
 1134.0,
 1133.0,
 1129.0,
 1130.0,
 1127.0,
 1133.0,
 1125.0,
 1130.0,
 1129.0,
 1133.0,
 1130.0,
 585.5,
 1132.0,
 578.0,
 1129.0,
 1129.0,
 578.0,
 1130.0,
 1128.0,
 1125.0,
 1133.0,
 1129.0,
 1133.0,
 1128.0,
 1134.0,
 1130.0,
 580.0,
 1130.0,
 1131.0,
 1130.0,
 1137.0,
 578.0,
 583.0,
 1130.0,
 578.0,
 1132.0,
 1135.0,
 1131.0,
 1130.0,
 578.0,
 1123.0,
 576.0,
 575.0,
 1132.0,
 1130.0,
 1129.0,
 1129.0,
 575.0,
 1131.0,
 1129.0,
 1130.0,
 1130.0,
 578.0,
 575.0,
 575.0,
 575.0,
 575.0,
 575.0,
 1131.0,
 578.0,
 1129.0,
 1130.0,
 1128.0,
 1133.0,
 1131.0,
 1129.0,
 1131.0,
 1132.0,
 1132.0,
 1127.0,
 1133.0,
 1132.0,
 575.0,
 1129.0,
 575.0,
 575.0,
 575.0,
 1128.0,
 575.0,
 1129.0,
 578.0,
 578.0,
 574.0,
 1131.0,
 1131.0,
 1129.0,
 1130.0,
 1131.0,
 1133.0,
 1123.0,
 1131.0,
 578.0,
 1133.0,
 1130.0,
 1131.0,
 1134.0,
 1128.0,
 1129.0,
 576.0,
 1130.0,
 1131.0,
 1134.0,
 566.0,
 570.5,
 1129.0,
 1130.0,
 1128.0,
 1125.0,
 1132.0,
 1130.0,
 1130.0,
 566.0,
 566.0,
 566.0,
 1129.0,
 1130.0,
 1129.0,
 565.0,
 1134.0,
 565.0,
 1130.0,
 565.0,
 1129.0,
 1132.0,
 560.0,
 1129.0,
 1130.0,
 560.0,
 1133.0,
 1132.0,
 560.0,
 1131.0,
 1123.0,
 1132.0,
 560.0,
 1128.0,
 1131.0,
 1130.0,
 1130.0,
 560.0,
 1133.0,
 560.0,
 1134.0,
 564.5,
 1128.0,
 1133.0,
 1127.0,
 1131.0,
 550.0,
 1136.0,
 1130.0,
 550.0,
 1131.0,
 1127.0,
 550.0,
 560.0,
 1127.0,
 560.0,
 1124.0,
 1130.0,
 1133.0,
 1132.0,
 1126.0,
 1134.0,
 550.0,
 1126.0,
 1132.0,
 1130.0,
 1128.0,
 545.0,
 1133.0,
 478.4,
 111.5,
 1129.0,
 1126.0,
 1131.0,
 1132.0,
 1134.0,
 1130.0,
 1132.0,
 1128.0,
 560.5,
 1132.0,
 1131.0,
 1130.0,
 1133.0,
 1130.0,
 1130.0,
 1128.0,
 545.0,
 477.4,
 1129.0,
 478.8,
 478.4,
 478.0,
 477.6,
 478.6,
 1131.0,
 1135.0,
 478.0,
 1129.0,
 477.4,
 1132.0,
 1131.0,
 1133.0,
 1130.0,
 545.0,
 1133.0,
 1130.0,
 1128.0,
 1130.0,
 1133.0,
 1134.0,
 546.0,
 1130.0,
 1130.0,
 1129.0,
 1126.0,
 478.6,
 478.8,
 477.4,
 478.0,
 478.4,
 189.5,
 1132.0,
 1129.0,
 560.0,
 189.2,
 478.0,
 535.0,
 1126.0,
 1133.0,
 550.0,
 1132.0,
 550.0,
 1126.0,
 1130.0,
 1127.0,
 1129.0,
 1128.0,
 545.0,
 189.9,
 1128.0,
 14.65,
 nan,
 nan,
 nan,
 nan,
 nan,
 1129.0,
 1129.0,
 1129.0,
 478.0,
 2.68,
 545.0,
 189.2,
 1129.0]